### PR TITLE
Project update

### PR DESCRIPTION
**Pull request by jingyuexing**
- [x] delete node_modules folder
- [x] delete vscodecounter folder
- [x] add ignore file
- [x] add editorconfig

### CODE REVIEW

**Comment by sheepbox8646** [comment]
Thank you ,but we working on coding.net so it maybe so bad ,but we can delete the node_model dir,Thank you,happy every day

**Comment by sheepbox8646** [comment]
so can you give we a star?(doge)

**Comment by jingyuexing** [comment]
> so can you give we a star?(doge)

maybe need standardized this project ,like add ignore file , editorconfig ,prettier config file, etc.

**Comment by samzhangjy** [comment]
Closed.

**Pull request closed without merging**
