### PR TITLE
Revert "Revert "第一次pr""

### PR DESCRIPTION
**Pull request by sheepbox8646**
Reverts Bug-Duck/tntjs#7

### CODE REVIEW

**Comment by sheepbox8646** [comment]
哎等等等等 你往TNT.里写干什么啊 我们平时用这个.ts文件写的好嘛 是typescript 你写的那个是编译产物啊

**Comment by mono2048** [comment]
Get It

**Comment by onion108** [comment]
mono2048 你好，首先感谢您对TNTJs的项目的贡献，但是这里的GitHub仓库已经是滞后的版本，我们内部的TNTJs从目录结构到运行原理已经全部重构了，如果您需要一份最新的项目结构的话可以联系我的QQ2916467374，我可以给您提供一份最新的项目副本并回答有关新的运行机制的问题，以方便您做出更为有效的贡献。再次感谢您的贡献。

Hello mono2048, firstly I have to thank for your contribution, but the repository here isn't the newest version. We rebuild the project recently and now the structure of the project and the runtime system are both different from this repository. If you need the newest project folder please contact me on QQ 2916467374, and I can provide you the newest project folder and answers any question about the new runtime system in order to make it easier for you to make more useful contribution. Thanks for your contribution again.

**Comment by onion108** [comment]
> Get It

mono2048 你好，首先感谢您对TNTJs的项目的贡献，但是这里的GitHub仓库已经是滞后的版本，我们内部的TNTJs从目录结构到运行原理已经全部重构了，如果您需要一份最新的项目结构的话可以联系我的QQ2916467374，我可以给您提供一份最新的项目副本并回答有关新的运行机制的问题，以方便您做出更为有效的贡献。再次感谢您的贡献。

Hello mono2048, firstly I have to thank for your contribution, but the repository here isn't the newest version. We rebuild the project recently and now the structure of the project and the runtime system are both different from this repository. If you need the newest project folder please contact me on QQ 2916467374, and I can provide you the newest project folder and answers any question about the new runtime system in order to make it easier for you to make more useful contribution. Thanks for your contribution again.

**Comment by samzhangjy** [comment]
Closed.

**Pull request closed without merging**
